cmake_minimum_required(VERSION 3.24)

project(mino_network_example_project)

add_subdirectory(download)
add_subdirectory(ftp)
add_subdirectory(interface)
add_subdirectory(log)
add_subdirectory(memory_store)
add_subdirectory(message_broker)
add_subdirectory(rest)
add_subdirectory(rpc)
add_subdirectory(sftp)
add_subdirectory(tcp)
add_subdirectory(udp)
add_subdirectory(util)
add_subdirectory(ws)
