cmake_minimum_required(VERSION 3.24)

project(mino_core_example_project)

add_subdirectory(bit)
add_subdirectory(broker)
add_subdirectory(config)
add_subdirectory(container)
add_subdirectory(convert)
add_subdirectory(crypt)
add_subdirectory(csv)
add_subdirectory(daemon)
add_subdirectory(datetime)
add_subdirectory(encoding)
add_subdirectory(enum)
add_subdirectory(expected)
add_subdirectory(file)
add_subdirectory(hash)
add_subdirectory(ini)

