cmake_minimum_required(VERSION 3.24)

project(mino_core_example_project)

add_subdirectory(bit)
add_subdirectory(broker)
add_subdirectory(config)
add_subdirectory(container)
add_subdirectory(convert)
add_subdirectory(crypt)
add_subdirectory(csv)
add_subdirectory(daemon)
add_subdirectory(datetime)
add_subdirectory(encoding)
add_subdirectory(enum)
add_subdirectory(expected)
add_subdirectory(file)
add_subdirectory(hash)
add_subdirectory(ini)
add_subdirectory(json)
add_subdirectory(log)
add_subdirectory(macro)
add_subdirectory(memory)
add_subdirectory(notification)
add_subdirectory(notifications)
add_subdirectory(overload)
add_subdirectory(pfr)
add_subdirectory(process_util)
add_subdirectory(reflect)
add_subdirectory(resilience)
add_subdirectory(result)
add_subdirectory(schedule)
add_subdirectory(server)
add_subdirectory(service)
add_subdirectory(shared_memory)
add_subdirectory(singleton)
add_subdirectory(string)
add_subdirectory(system)
add_subdirectory(thread)
add_subdirectory(tpm)
add_subdirectory(uuid)
add_subdirectory(validation)
add_subdirectory(xml)
add_subdirectory(yaml)
